- name: problem
  description: Get problem from website
  color: C13442
- name: contribution
  description: Architecture is clear and community can help
  color: F488C1
- name: documentation
  description: Improvements or additions to documentation
  color: 0075CA
- name: ready to merge
  description: ready
  color: 0E8A16
- name: review
  description: review
  color: 5319E7
