name: 🤖 Auto sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/labels.yml
          token: ${{ secrets.NEVEXBOT_TOKEN }}
          repository: |
            nevex-net/.github
            nevex-net/nevex.net
            nevex-net/app
            nevex-net/backend
            nevex-net/nevex.net
